#!/usr/bin/perl -w -Ilib/
#
#  Test that all the Perl modules we require are available.
#
#  This list is automatically generated by modules.sh
#

use Test::More qw( no_plan );

BEGIN{ use_ok( 'Application::Ajax' ); }
require_ok( 'Application::Ajax' );
BEGIN{ use_ok( 'Application::Feeds' ); }
require_ok( 'Application::Feeds' );
BEGIN{ use_ok( 'Application::Yawns' ); }
require_ok( 'Application::Yawns' );
BEGIN{ use_ok( 'base' ); }
require_ok( 'base' );
BEGIN{ use_ok( 'Cache::Memcached' ); }
require_ok( 'Cache::Memcached' );
BEGIN{ use_ok( 'CGI' ); }
require_ok( 'CGI' );
BEGIN{ use_ok( 'CGI::Carp' ); }
require_ok( 'CGI::Carp' );
BEGIN{ use_ok( 'CGI::Cookie' ); }
require_ok( 'CGI::Cookie' );
BEGIN{ use_ok( 'CGI::Fast' ); }
require_ok( 'CGI::Fast' );
BEGIN{ use_ok( 'CGI::Session' ); }
require_ok( 'CGI::Session' );
BEGIN{ use_ok( 'conf::SiteConfig' ); }
require_ok( 'conf::SiteConfig' );
BEGIN{ use_ok( 'constant' ); }
require_ok( 'constant' );
BEGIN{ use_ok( 'Data::Dumper' ); }
require_ok( 'Data::Dumper' );
BEGIN{ use_ok( 'Date::Format' ); }
require_ok( 'Date::Format' );
BEGIN{ use_ok( 'Date::Parse' ); }
require_ok( 'Date::Parse' );
BEGIN{ use_ok( 'DBI' ); }
require_ok( 'DBI' );
BEGIN{ use_ok( 'File::Basename' ); }
require_ok( 'File::Basename' );
BEGIN{ use_ok( 'File::Find' ); }
require_ok( 'File::Find' );
BEGIN{ use_ok( 'File::Path' ); }
require_ok( 'File::Path' );
BEGIN{ use_ok( 'Getopt::Long' ); }
require_ok( 'Getopt::Long' );
BEGIN{ use_ok( 'HTML::AddNoFollow' ); }
require_ok( 'HTML::AddNoFollow' );
BEGIN{ use_ok( 'HTML::Balance' ); }
require_ok( 'HTML::Balance' );
BEGIN{ use_ok( 'HTML::BreakupText' ); }
require_ok( 'HTML::BreakupText' );
BEGIN{ use_ok( 'HTML::Entities' ); }
require_ok( 'HTML::Entities' );
BEGIN{ use_ok( 'HTML::Linkize' ); }
require_ok( 'HTML::Linkize' );
BEGIN{ use_ok( 'HTML::Parser' ); }
require_ok( 'HTML::Parser' );
BEGIN{ use_ok( 'HTML::Template' ); }
require_ok( 'HTML::Template' );
BEGIN{ use_ok( 'HTML::TokeParser' ); }
require_ok( 'HTML::TokeParser' );
BEGIN{ use_ok( 'HTML::TreeBuilder' ); }
require_ok( 'HTML::TreeBuilder' );
BEGIN{ use_ok( 'IO::File' ); }
require_ok( 'IO::File' );
BEGIN{ use_ok( 'IO::Socket' ); }
require_ok( 'IO::Socket' );
BEGIN{ use_ok( 'JSON' ); }
require_ok( 'JSON' );
BEGIN{ use_ok( 'Lucy::Simple' ); }
require_ok( 'Lucy::Simple' );
BEGIN{ use_ok( 'LWP::Simple' ); }
require_ok( 'LWP::Simple' );
BEGIN{ use_ok( 'Mail::Verify' ); }
require_ok( 'Mail::Verify' );
BEGIN{ use_ok( 'Pod::Checker' ); }
require_ok( 'Pod::Checker' );
BEGIN{ use_ok( 'Pod::Parser' ); }
require_ok( 'Pod::Parser' );
BEGIN{ use_ok( 'Pod::Usage' ); }
require_ok( 'Pod::Usage' );
BEGIN{ use_ok( 'Singleton::DBI' ); }
require_ok( 'Singleton::DBI' );
BEGIN{ use_ok( 'strict' ); }
require_ok( 'strict' );
BEGIN{ use_ok( 'String::Approx' ); }
require_ok( 'String::Approx' );
BEGIN{ use_ok( 'Sys::CpuLoad' ); }
require_ok( 'Sys::CpuLoad' );
BEGIN{ use_ok( 'TAP::Harness' ); }
require_ok( 'TAP::Harness' );
BEGIN{ use_ok( 'Template' ); }
require_ok( 'Template' );
BEGIN{ use_ok( 'Test::More' ); }
require_ok( 'Test::More' );
BEGIN{ use_ok( 'Text::Diff' ); }
require_ok( 'Text::Diff' );
BEGIN{ use_ok( 'Text::Markdown' ); }
require_ok( 'Text::Markdown' );
BEGIN{ use_ok( 'Text::Textile' ); }
require_ok( 'Text::Textile' );
BEGIN{ use_ok( 'URI' ); }
require_ok( 'URI' );
BEGIN{ use_ok( 'URI::Find' ); }
require_ok( 'URI::Find' );
BEGIN{ use_ok( 'utf8' ); }
require_ok( 'utf8' );
BEGIN{ use_ok( 'vars' ); }
require_ok( 'vars' );
BEGIN{ use_ok( 'warnings' ); }
require_ok( 'warnings' );
BEGIN{ use_ok( 'Yawns::About' ); }
require_ok( 'Yawns::About' );
BEGIN{ use_ok( 'Yawns::Adverts' ); }
require_ok( 'Yawns::Adverts' );
BEGIN{ use_ok( 'Yawns::Article' ); }
require_ok( 'Yawns::Article' );
BEGIN{ use_ok( 'Yawns::Articles' ); }
require_ok( 'Yawns::Articles' );
BEGIN{ use_ok( 'Yawns::Bookmarks' ); }
require_ok( 'Yawns::Bookmarks' );
BEGIN{ use_ok( 'Yawns::Cache' ); }
require_ok( 'Yawns::Cache' );
BEGIN{ use_ok( 'Yawns::Comment' ); }
require_ok( 'Yawns::Comment' );
BEGIN{ use_ok( 'Yawns::Comment::Notifier' ); }
require_ok( 'Yawns::Comment::Notifier' );
BEGIN{ use_ok( 'Yawns::Comments' ); }
require_ok( 'Yawns::Comments' );
BEGIN{ use_ok( 'Yawns::Date' ); }
require_ok( 'Yawns::Date' );
BEGIN{ use_ok( 'Yawns::Event' ); }
require_ok( 'Yawns::Event' );
BEGIN{ use_ok( 'Yawns::Formatters' ); }
require_ok( 'Yawns::Formatters' );
BEGIN{ use_ok( 'Yawns::Formatters::HTML' ); }
require_ok( 'Yawns::Formatters::HTML' );
BEGIN{ use_ok( 'Yawns::Formatters::Markdown' ); }
require_ok( 'Yawns::Formatters::Markdown' );
BEGIN{ use_ok( 'Yawns::Formatters::Text' ); }
require_ok( 'Yawns::Formatters::Text' );
BEGIN{ use_ok( 'Yawns::Formatters::Textile' ); }
require_ok( 'Yawns::Formatters::Textile' );
BEGIN{ use_ok( 'Yawns::Mailer' ); }
require_ok( 'Yawns::Mailer' );
BEGIN{ use_ok( 'Yawns::Permissions' ); }
require_ok( 'Yawns::Permissions' );
BEGIN{ use_ok( 'Yawns::Poll' ); }
require_ok( 'Yawns::Poll' );
BEGIN{ use_ok( 'Yawns::Polls' ); }
require_ok( 'Yawns::Polls' );
BEGIN{ use_ok( 'Yawns::Preferences' ); }
require_ok( 'Yawns::Preferences' );
BEGIN{ use_ok( 'Yawns::RSS' ); }
require_ok( 'Yawns::RSS' );
BEGIN{ use_ok( 'Yawns::Scratchpad' ); }
require_ok( 'Yawns::Scratchpad' );
BEGIN{ use_ok( 'Yawns::Sidebar' ); }
require_ok( 'Yawns::Sidebar' );
BEGIN{ use_ok( 'Yawns::Stats' ); }
require_ok( 'Yawns::Stats' );
BEGIN{ use_ok( 'Yawns::Submissions' ); }
require_ok( 'Yawns::Submissions' );
BEGIN{ use_ok( 'Yawns::Tags' ); }
require_ok( 'Yawns::Tags' );
BEGIN{ use_ok( 'Yawns::User' ); }
require_ok( 'Yawns::User' );
BEGIN{ use_ok( 'Yawns::Users' ); }
require_ok( 'Yawns::Users' );
BEGIN{ use_ok( 'Yawns::Weblog' ); }
require_ok( 'Yawns::Weblog' );
BEGIN{ use_ok( 'Yawns::Weblogs' ); }
require_ok( 'Yawns::Weblogs' );
