#!/bin/sh
#
#  Automatically attempt to create a test which ensures all the modules
# used in the code are availabe.
#
# Steve
# --
# http://www.steve.org.uk/
#
# $Id: modules.sh,v 1.5 2006-02-07 18:35:33 steve Exp $
#

cat <<EOF
#!/usr/bin/perl -w -Ilib/
#
#  Test that all the Perl modules we require are available.
#
#  This list is automatically generated by modules.sh
#

use Test::More qw( no_plan );

EOF


for i in `rgrep '^use ' .. | grep -v stats | grep -v accessors | grep -v TAP::Fo | grep -v feature | grep -v 5 | grep -v file |grep -v POSIX | awk '{print $2}' | tr -d \;\(\) | sort | uniq`; \
    do \
     echo "BEGIN{ use_ok( '$i' ); }"; \
     echo "require_ok( '$i' );" ; \

done

